### ISSUE TITLE
[Bug]: After I updated fvtt, PF2e system got error "Invalid mapping JavaScript Object".

### ISSUE THREAD

**Issue by kagangtuya-star** [arcanistzed/pdf-sheet#112]
### Expected Behavior

When uploading the PF2e character sheet PDF, a window appears that shows all the fillable fields on the PDF. 

### Current Behavior

```
foundry.js:68241  PDF Sheet | Invalid mapping JavaScript Object. See the <a href="https://github.com/arcanistzed/pdf-sheet/blob/main/README.md">README</a> for more info.
fetch @ foundry.js:68241
notify @ foundry.js:68138
error @ foundry.js:68175
createForm @ pdfsheet.js:374
onFileUpload @ pdfsheet.js:508
reader.onload @ pdfsheet.js:296
load(异步)
(anonymous) @ pdfsheet.js:296
VM254710:3  Uncaught TypeError: Cannot read properties of undefined (reading 'unarmored')
    at eval (eval at createForm (pdfsheet.js:379:4), <anonymous>:3:2899)
    at Pdfconfig.createForm (pdfsheet.js:379:77)
    at Pdfconfig.onFileUpload (pdfsheet.js:508:8)
    at reader.onload (pdfsheet.js:296:31)
```

Foundry Virtual Tabletop v11.313

System: Pathfinder 2nd Edition5.7.2

After I updated fvtt, PF2e system got error

### Steps to Reproduce

![image](https://github.com/arcanistzed/pdf-sheet/assets/73411104/a2d891f2-64f5-465b-a004-a74fa088ecff)
Do the above options and import the correct PDF...

### Context

![image](https://github.com/arcanistzed/pdf-sheet/assets/73411104/37d6fe97-4cee-478c-aa6e-b37e8569fc2e)

### Version

0.24.1

### Foundry VTT Version

11.313

### Operating System

Windows

### Browser / App

Chrome

### Game System

PF2E v5.7.2

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by Warbier89** [comment]
I have sadly exactly the same problem with the 11 Stable Build 315 version of FoundryVTT in combination with the DnD5e - Fifth Edition System 2.3.1:
![image](https://github.com/arcanistzed/pdf-sheet/assets/15850207/d654ff00-660c-40d4-82be-c41e8aad2fe0)

**Comment by davelamorte** [comment]
Upon further testing, it's the field "languages".
If it has anything more than one language, the issue appears.

**Comment by ksignorini** [comment]
Oh no! Will this be fixed?

**Comment by ksignorini** [comment]
> Upon further testing, it's the field "languages". If it has anything more than one language, the issue appears.

Removing the mapping for Languages (commenting out the section) doesn't seem to fix it though. Ideas?
