### ISSUE TITLE
[Bug]: Issue exporting D&D Sheet on Foundry 10 and D&D 2.1.2

### ISSUE THREAD

**Issue by rrlevy** [arcanistzed/pdf-sheet#64]
### Expected Behavior

Export with default dnd5e mapping to work correctly

### Current Behavior

When exporting the sheet with the default dnd5e mapping, I get an error:

![image](https://user-images.githubusercontent.com/14061585/213522450-de98cfdc-a12e-4dd5-b884-c821f8f667bb.png)

```
VM35092:3 Uncaught TypeError: actor.data.data.traits.weaponProf.value.map(...).concat is not a function
[Detected 1 package: pdf-sheet]
    at eval (eval at createForm (pdfsheet.js:264:4), <anonymous>:3:10512)
    at eval (eval at createForm (pdfsheet.js:264:4), <anonymous>:3:11750)
    at Pdfconfig.createForm (pdfsheet.js:264:77)
    at Pdfconfig.onFileUpload (pdfsheet.js:393:8)
    at reader.onload (pdfsheet.js:192:31)
```

![image](https://user-images.githubusercontent.com/14061585/213514578-34e695e5-793d-4974-a522-78aeba350884.png)

If I remove the "ProficienciesLang" section from the mapping file, it works, but without the proficiencies section being mapped, of course.

### Steps to Reproduce

1. Have a character on Foundry 10 and D&D 5e version 2.1.2 with proficiencies set
2. No modules enabled, only pdf-sheet
3. Configure module with default dnd5e mapping
4. Try to export the character sheet
5. Will show error in Foundry and specific information about it as above on console

### Context

There are also plenty of warnings regardin the use of deprecated variables:

![image](https://user-images.githubusercontent.com/14061585/213515128-0feed3ec-9563-45b4-96e9-7f5564c92426.png)

### Version

0.22.3

### Foundry VTT Version

10.291

### Operating System

Linux AWS

### Browser / App

Chrome

### Game System

dnd5e (2.1.2)

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by rrlevy** [comment]
Just additional info: even if you create AN EMPTY NEW player, the export fails with the same error

**Comment by SebaSOFT** [comment]
See mi pull request #68 It should fix this

**Comment by Matt-BW** [comment]
Same issue for me, can't seem to fix it even with the pull request above.

**Comment by ethernetguru** [comment]
same issue with me.

**Comment by slyandsmart** [comment]
Hi,
i have the same problem with Foundry 10.303, DND5 2.3.1 and  ExportSheettoPDF 0.24.0.

Hope you can help with that. I tried different mappings and pdfs.

**Comment by EvilRenegade** [comment]
This issue went away for me after updating everything to the latest version - FVTT 11.309, D&D 2.3.1 and PDF Export 0.24.0, using Mapping dnd5eV11.

**Comment by davelamorte** [comment]
Upon further testing, it's the field "languages".
If it has anything more than one language, the issue appears.
