### ISSUE TITLE
[Bug]: PF1 Mapping/ Export broken

### ISSUE THREAD

**Issue by Calcemo** [arcanistzed/pdf-sheet#76]
### Expected Behavior

Being able to export a PF1 character as PDF.

### Current Behavior

Cannot export a character.

### Steps to Reproduce

1. Create Character
2. Open character Sheet
3. Try to export to PDF using the suggested PDF as input

### Context

The message "PDF Sheet | Invalid mapping JavaScript Object. See the <a href="https://github.com/arcanistzed/pdf-sheet/blob/main/README.md">README</a> for more info." shows up.

Also theres an uncaught type error:
"Uncaught TypeError: undefined. Cannot read properties of undefined (reading 'ac')
[Detected 1 package: pdf-sheet]
    at eval (eval at createForm (pdfsheet.js:264:4), <anonymous>:3:3464)
    at Pdfconfig.createForm (pdfsheet.js:264:77)
    at Pdfconfig.onFileUpload (pdfsheet.js:393:8)
    at reader.onload (pdfsheet.js:192:31)"
    
Also also, theres tons of warnings for deprecated usage like this:
"Error: You are accessing the ActorCharacterPF#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly."

and this:
"Error: You are accessing ActorCharacterPF#data which has been migrated to ActorCharacterPF#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12"

### Version

0.22.4

### Foundry VTT Version

10.291

### Operating System

Windows

### Browser / App

Native Electron App

### Game System

Pf1 0.82.5

### Modules Disabled

- [X] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by arvoituksellinen** [comment]
I have fixed the breaking changes issue in the data model in:
-  [Pending]https://github.com/arcanistzed/pdf-sheet/pull/79

However the warnings for deprecated usage are still present and will need to be fixed before version 12 of Foundry vtt.
