### ISSUE TITLE
[Bug]: V11 dnd5e not working

### ISSUE THREAD

**Issue by gioppoluca** [arcanistzed/pdf-sheet#81]
### Expected Behavior

Manage to export

### Current Behavior

```
Error: You are accessing the Actor5e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1993:19)
    at Actor5e._logV10CompatibilityWarning (commons.js:8440:14)
    at get data [as data] (commons.js:8328:24)
    at eval (eval at createForm (pdfsheet.js:264:4), <anonymous>:3:10617)
    at eval (eval at createForm (pdfsheet.js:264:4), <anonymous>:3:11422)
    at Pdfconfig.createForm (pdfsheet.js:264:77)
    at Pdfconfig.onFileUpload (pdfsheet.js:393:8)
    at reader.onload (pdfsheet.js:192:31)
logCompatibilityWarning @ commons.js:2004
commons.js:2004 Error: You are accessing the Actor5e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1993:19)
    at Actor5e._logV10CompatibilityWarning (commons.js:8440:14)
    at get data [as data] (commons.js:8328:24)
    at eval (eval at createForm (pdfsheet.js:264:4), <anonymous>:3:10785)
    at eval (eval at createForm (pdfsheet.js:264:4), <anonymous>:3:11422)
    at Pdfconfig.createForm (pdfsheet.js:264:77)
    at Pdfconfig.onFileUpload (pdfsheet.js:393:8)
    at reader.onload (pdfsheet.js:192:31)
logCompatibilityWarning @ commons.js:2004
VM11104:3 Uncaught TypeError: undefined. Cannot read properties of undefined (reading 'value')
[Detected 1 package: pdf-sheet]
    at eval (eval at createForm (pdfsheet.js:264:4), <anonymous>:3:10813)
    at eval (eval at createForm (pdfsheet.js:264:4), <anonymous>:3:11422)
    at Pdfconfig.createForm (pdfsheet.js:264:77)
    at Pdfconfig.onFileUpload (pdfsheet.js:393:8)
    at reader.onload (pdfsheet.js:192:31)
```

### Steps to Reproduce

Usual steps:
1. enable module
2. configure module: select dnd5e (but the format of the content get a bit mangled afterwards)
3. export from char sheet

### Context

V11
same red errors shown in other issues

### Version

0.22.4

### Foundry VTT Version

V11.300

### Operating System

Linux

### Browser / App

Chrome

### Game System

dnd5e

### Modules Disabled

- [ ] I can confirm that disabling all of my other modules doesn't fix this issue.

**Comment by enikesa82** [comment]
I can confirm I am also getting this on v11.300 
![image](https://github.com/arcanistzed/pdf-sheet/assets/107894060/f4976ea0-dbbb-4ecb-ae06-59c6b95566a7)

**Comment by GinjiJizai** [comment]
I can confirm this, too. Can someone help here?

**Comment by GinjiJizai** [comment]
@enikesa82 @gioppoluca 

Hi everyone,

i found the line in the DND5e Sheet, thats causing the issue:
```
a = @system.traits.toolProf.value.map(x => game.dnd5e.config.toolProficiencies[x]
  || game.packs.get("dnd5e.items").index.get(game.dnd5e.config.toolIds[x])?.name).first();
  b = @system.traits.toolProf.custom.split(";").filter(x => String(x) && x?.length);
  if (a?.length > 0) { s = `${s}Tools: ${a} ${b.join(', ')}\n`; }
```
  

It seems, like the toolProf is an empty variable. If you comment this lines out, you can export your character, even if the warning messages persist in the console.

I hope this workarround helps some ppl for now, but it would be cool if someone with more knowledge about the data structure could find a fix for this.

**Comment by gioppoluca** [comment]
If you get the file from the merge request I did you should have a v11 working mapping

**Comment by GinjiJizai** [comment]
@gioppoluca 

thank you very much :)
